/*
-----------------------------------------------------------------------------
Filename:    OgreTest1.h
-----------------------------------------------------------------------------

This source file is generated by the Ogre AppWizard.

Check out: http://conglomerate.berlios.de/wiki/doku.php?id=ogrewizards

Based on the Example Framework for OGRE
(Object-oriented Graphics Rendering Engine)

Copyright (c) 2000-2007 The OGRE Team
For the latest info, see http://www.ogre3d.org/

You may use this sample code for anything you like, it is not covered by the
LGPL like the rest of the OGRE engine.
-----------------------------------------------------------------------------
*/
#ifndef __OgreTest1_h_
#define __OgreTest1_h_


#include "BaseApplication.h"
#if OGRE_PLATFORM == OGRE_PLATFORM_WIN32
#include "../res/resource.h"
#endif

class OgreTest1App : public BaseApplication
{
public:
	OgreTest1App(void);
	virtual ~OgreTest1App(void);
protected:
	virtual void createScene(void);
	virtual bool frameEnded(const FrameEvent& evt);
	GeoClipmapPatch* patch;
};


#endif // #ifndef __OgreTest1_h_